runtime: python311

env_variables:
  # Database Configuration
  DB_DRIVER: "MariaDB Unicode"
  DB_SERVER: "34.152.118.156"
  DB_DATABASE: "odcb_databridge-db"
  DB_USERNAME: "odcb-databridge-db"
  DB_PASSWORD: "YOUR_PASSWORD_HERE"  # Replace with actual password before deploying
  DB_PORT: "3306"
  
  # API Endpoints
  BIRDEYE_ENDPOINT: "https://hooks.zapier.com/hooks/catch/23151206/umyaaov/"
  EXAMPLE_SERVICE_ENDPOINT: "https://hooks.zapier.com/hooks/catch/23151206/umyaaov/"
  
  # Logging
  LOG_DIR: "logs"
  LOG_LEVEL: "INFO"

entrypoint: gunicorn -b :$PORT api:app
